FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy csproj and restore as distinct layers
COPY ScoringTablet/ScoringTablet.csproj ScoringTablet/
RUN dotnet restore ScoringTablet/ScoringTablet.csproj

# Copy everything else and build
COPY ScoringTablet/. ScoringTablet/
WORKDIR /src/ScoringTablet
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ScoringTablet.dll"]
